//! Build-time compilation of vue-rs `.vrs` single-file components.

use std::fmt;
use std::path::{Path, PathBuf};

/// A build-time failure (bad `.vrs` name or a compile error), with a message.
#[derive(Debug)]
pub struct BuildError(pub String);

impl fmt::Display for BuildError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}
impl std::error::Error for BuildError {}

/// The PascalCase component name for a `.vrs` file stem
/// (`todo_app` -> `TodoApp`, `counter` -> `Counter`).
pub fn component_name(stem: &str) -> String {
    stem.split('_')
        .filter(|s| !s.is_empty())
        .map(|word| {
            let mut c = word.chars();
            match c.next() {
                Some(first) => first.to_ascii_uppercase().to_string() + c.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

/// Compile one `.vrs` source into formatted Rust source text: the component's
/// `pub fn <Name><B>` render function and its supporting items. `stem` is the
/// file stem (its PascalCase form names the component); `scope_seed` is a stable
/// per-file path used for the scoped-style id.
pub fn compile_source(stem: &str, source: &str, scope_seed: &str) -> Result<String, BuildError> {
    let name = component_name(stem);
    let ident = proc_macro2::Ident::new(&name, proc_macro2::Span::call_site());
    let tokens = vue_rs_compiler::compile_component(&ident, source, scope_seed, None)
        .map_err(|e| BuildError(format!("{scope_seed}: {e}")))?;
    let file: syn::File = syn::parse2(tokens)
        .map_err(|e| BuildError(format!("{scope_seed}: generated invalid Rust: {e}")))?;
    Ok(prettyplease::unparse(&file))
}

/// Call this from `build.rs`. Scans `dir` (relative to `CARGO_MANIFEST_DIR`)
/// recursively for `*.vrs`, compiles each, and writes `$OUT_DIR/vrs/<stem>.rs`
/// plus `$OUT_DIR/vue_rs_components.rs`. Each component lives in its own `mod`,
/// so the `use` items its `<script>` hoists are module-scoped. Include the
/// aggregator from your crate:
/// `include!(concat!(env!("OUT_DIR"), "/vue_rs_components.rs"));`
pub fn compile_dir(dir: impl AsRef<Path>) -> Result<(), BuildError> {
    let manifest = std::env::var("CARGO_MANIFEST_DIR")
        .map_err(|_| BuildError("CARGO_MANIFEST_DIR not set (call from build.rs)".into()))?;
    let out = std::env::var("OUT_DIR")
        .map_err(|_| BuildError("OUT_DIR not set (call from build.rs)".into()))?;
    let root = PathBuf::from(&manifest);
    let scan_root = root.join(dir.as_ref());

    println!("cargo:rerun-if-changed={}", scan_root.display());

    let mut vrs_files = Vec::new();
    collect_vrs(&scan_root, &mut vrs_files)?;
    vrs_files.sort(); // deterministic output

    let vrs_out = PathBuf::from(&out).join("vrs");
    std::fs::create_dir_all(&vrs_out).map_err(|e| BuildError(e.to_string()))?;

    let mut mods = Vec::new();
    for path in &vrs_files {
        println!("cargo:rerun-if-changed={}", path.display());
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .ok_or_else(|| BuildError(format!("bad .vrs file name: {}", path.display())))?
            .to_string();
        let source = std::fs::read_to_string(path).map_err(|e| BuildError(e.to_string()))?;
        // Seed = path relative to the crate root, for a stable scope id.
        let seed = path
            .strip_prefix(&root)
            .unwrap_or(path)
            .to_string_lossy()
            .replace('\\', "/");
        let rust = compile_source(&stem, &source, &seed)?;
        let header = format!("// @generated from {seed} by vue-rs-build. Do not edit.\n");
        std::fs::write(vrs_out.join(format!("{stem}.rs")), header + &rust)
            .map_err(|e| BuildError(e.to_string()))?;
        mods.push((stem.clone(), component_name(&stem)));
    }

    let mut agg = String::from("// @generated by vue-rs-build. Do not edit.\npub mod components {\n");
    for (stem, name) in &mods {
        agg.push_str(&format!(
            "    pub mod {stem} {{ include!(concat!(env!(\"OUT_DIR\"), \"/vrs/{stem}.rs\")); }}\n"
        ));
        agg.push_str(&format!("    pub use {stem}::{name};\n"));
    }
    agg.push_str("}\n");
    std::fs::write(PathBuf::from(&out).join("vue_rs_components.rs"), agg)
        .map_err(|e| BuildError(e.to_string()))?;
    Ok(())
}

/// Recursively collect every `*.vrs` file found under `dir` into `out`.
fn collect_vrs(dir: &Path, out: &mut Vec<PathBuf>) -> Result<(), BuildError> {
    if !dir.exists() {
        return Err(BuildError(format!(
            "directory does not exist: {}",
            dir.display()
        )));
    }
    for entry in std::fs::read_dir(dir).map_err(|e| BuildError(e.to_string()))? {
        let entry = entry.map_err(|e| BuildError(e.to_string()))?;
        let path = entry.path();
        if path.is_dir() {
            collect_vrs(&path, out)?;
        } else if path.extension().and_then(|e| e.to_str()) == Some("vrs") {
            out.push(path);
        }
    }
    Ok(())
}
